name: Update Dependencies

on:
  schedule:
# Runs at 00:00 on Wednesday
    - cron: '0 0 * * 3'

jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set remote url
        run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Update package.json
        uses: taichi/actions-package-update@master
        env:
          AUTHOR_EMAIL: ashikkumar23@gmail.com
          AUTHOR_NAME: Ashik Kumar
          EXECUTE: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: debug
        with:
          args: -u --packageFile package.json --loglevel verbose
